#!/bin/sh
set -euo pipefail
[ ! -d "bin" ] && mkdir bin
[ -d "bin/deno" ] && rm bin/deno
curl -fsSL https://github.com/denoland/deno/releases/download/v1.39.1/deno-x86_64-unknown-linux-gnu.zip -o deno-linux.zip
unzip deno-linux.zip -d bin
rm deno-linux.zip
zip lambda-deno-runtime.zip bootstrap bin/deno runtime.js
rm bin/deno
rmdir bin
aws lambda publish-layer-version --layer-name deno --description "Deno Runtime" --license-info "MIT" --zip-file fileb://lambda-deno-runtime.zip
rm lambda-deno-runtime.zip