#!/bin/sh
set -euo pipefail
[ ! -d "bin" ] && mkdir bin
curl -fsSL https://github.com/denoland/deno/releases/download/v1.16.1/deno-x86_64-unknown-linux-gnu.zip -o /tmp/deno-linux.zip
unzip /tmp/deno-linux.zip -d bin
rm /tmp/deno-linux.zip
deno bundle runtime.ts runtime.js
zip lambda-deno-runtime.zip bootstrap bin/deno runtime.js
aws lambda publish-layer-version --layer-name deno --description "Deno Runtime" --license-info "MIT" --zip-file fileb://lambda-deno-runtime.zip